"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class env_state(object):
    __slots__ = ["timestamp", "joint_position", "joint_velocity", "object_position", "object_orientation"]

    __typenames__ = ["int64_t", "float", "float", "float", "float"]

    __dimensions__ = [None, [7], [4], [3], [4]]

    def __init__(self):
        self.timestamp = 0
        self.joint_position = [ 0.0 for dim0 in range(7) ]
        self.joint_velocity = [ 0.0 for dim0 in range(4) ]
        self.object_position = [ 0.0 for dim0 in range(3) ]
        self.object_orientation = [ 0.0 for dim0 in range(4) ]

    def encode(self):
        buf = BytesIO()
        buf.write(env_state._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.timestamp))
        buf.write(struct.pack('>7f', *self.joint_position[:7]))
        buf.write(struct.pack('>4f', *self.joint_velocity[:4]))
        buf.write(struct.pack('>3f', *self.object_position[:3]))
        buf.write(struct.pack('>4f', *self.object_orientation[:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != env_state._get_packed_fingerprint():
            raise ValueError("Decode error")
        return env_state._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = env_state()
        self.timestamp = struct.unpack(">q", buf.read(8))[0]
        self.joint_position = struct.unpack('>7f', buf.read(28))
        self.joint_velocity = struct.unpack('>4f', buf.read(16))
        self.object_position = struct.unpack('>3f', buf.read(12))
        self.object_orientation = struct.unpack('>4f', buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if env_state in parents: return 0
        tmphash = (0x7e7d86576948dc51) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if env_state._packed_fingerprint is None:
            env_state._packed_fingerprint = struct.pack(">Q", env_state._get_hash_recursive([]))
        return env_state._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

